name: Docker Build and Push

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build_and_push:
    name: ğŸ‹ Build and push
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“« Checkout
        uses: actions/checkout@v3.3.0
      - name: ğŸ’‰ Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4.3.0
        with:
          short-length: 8
      - name: ğŸ·ï¸ Set up tags
        id: meta
        uses: docker/metadata-action@v4.0.1
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/younited/pyredis-dump
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - name: âš™ï¸ Set up QEMU
        uses: docker/setup-qemu-action@v2.0.0
      - name: âš™ï¸ Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.0.0
      - name: ğŸ”‘ Login to GitHub Container Registry
        uses: docker/login-action@v2.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: ğŸ‹ Build and push
        uses: docker/build-push-action@v3.3.0
        with:
          file: ./Dockerfile
          push: ${{ startsWith(github.ref, 'refs/tags/v') }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
